apiVersion: apps/v1
kind: Deployment
metadata:
  name: pig-game-d
  labels:
    tier: frontend
    app: pig-game
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: pig-game 
  template:
    metadata:
      labels:
        app: pig-game
    spec:
      containers:
        - name: pig-game
          image: shantanudock/pig_game:first
          ports:
          - containerPort: 80