apiVersion: v1
kind: Service
metadata: 
  name: pig-game-service
  labels: 
    app: pig-game
    name: pig-game
spec: 
  ports: 
    - port: 8081
      targetPort: 80
  selector: 
    app: pig-game
    tier: frontend
  type: ClusterIP